"""Added Transaction Table

Revision ID: f8adace5d6fa
Revises: 60494ed561bd
Create Date: 2026-05-21 12:34:23.374365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8adace5d6fa'
down_revision: Union[str, Sequence[str], None] = '60494ed561bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('source_inventory_id', sa.Integer(), nullable=True),
    sa.Column('destination_inventory_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('ADD', 'REMOVE', 'TRANSFER', 'ADJUSTMENT', name='transaction_type'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['destination_inventory_id'], ['inventory.id'], name='fk_destination_inventory', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='fk_transaction_product', onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_inventory_id'], ['inventory.id'], name='fk_source_inventory', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    # ### end Alembic commands ###
